### PR TITLE
(feat) add schema

### PR DESCRIPTION
**Pull request by hhyi01**

### CODE REVIEW

**Review by elenabartosh — COMMENTED** [review]
Do we need listed_price for item_detail table?

**Review by TiffyB — COMMENTED** [review]
Looks good! Could we limit wholesale_price and list_price to decimal(7, 2)? There may be data transfer issues later if there are numbers higher than this.

**Review by elenabartosh — CHANGES_REQUESTED** [review]
Do we need listed_price for item_detail table?

**Comment by hhyi01** [comment]
Submitted changes to feat/schema.  Removed listed_price from item_detail table and limited wholesale_price and listed_price to decimal(7, 2).

**Pull request merged**
